import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { db } from "@/lib/db";

const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "c1pher.io",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
