import { ThemeProvider } from "@/providers/theme-provider";
import { SessionProvider } from "next-auth/react";
import { Nunito } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import { auth } from "@/auth";
import type { Metadata } from "next";
import "./globals.css";

const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "c1pher.io",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={font.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
            ><Toaster />
              {children}
            </ThemeProvider>
          </body>
      </html>
    </SessionProvider>
  );
}
